MedMasters-clinic-app/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Klinika.Controllers
{
    public class MenuController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MedMasters-clinic-app/Controllers/PatientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Klinika.Models;

namespace Klinika.Controllers
{
    public class PatientsController : Controller
    {
        private readonly masterContext _context;

        public PatientsController(masterContext context)
        {
            _context = context;
        }

        // GET: Patients
        public async Task<IActionResult> Index()
        {
            return View(await _context.Patients.ToListAsync());
        }

        // GET: Patients/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patients = await _context.Patients
                .FirstOrDefaultAsync(m => m.Pesel == id);
            if (patients == null)
            {
                return NotFound();
            }

            return View(patients);
        }

        // GET: Patients/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Patients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Pesel,Surname,MaidenName,Forename,SecondForename,Sex,DateOfBirth,DateOfDeath,CityOfBirth,City,Street,BuildingNumber,FlatNumber,PhoneNumber,Email,Active")] Patients patients)
        {
            if (ModelState.IsValid)
            {
                _context.Add(patients);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(patients);
        }

        // GET: Patients/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patients = await _context.Patients.FindAsync(id);
            if (patients == null)
            {
                return NotFound();
            }
            return View(patients);
        }

        // POST: Patients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Pesel,Surname,MaidenName,Forename,SecondForename,Sex,DateOfBirth,DateOfDeath,CityOfBirth,City,Street,BuildingNumber,FlatNumber,PhoneNumber,Email,Active")] Patients patients)
        {
            if (id != patients.Pesel)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(patients);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PatientsExists(patients.Pesel))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(patients);
        }

        // GET: Patients/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patients = await _context.Patients
                .FirstOrDefaultAsync(m => m.Pesel == id);
            if (patients == null)
            {
                return NotFound();
            }

            return View(patients);
        }

        // POST: Patients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var patients = await _context.Patients.FindAsync(id);
            _context.Patients.Remove(patients);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PatientsExists(string id)
        {
            return _context.Patients.Any(e => e.Pesel == id);
        }
    }
}

MedMasters-clinic-app/Controllers/VisitsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Klinika.Models;

namespace Klinika.Controllers
{
    public class VisitsController : Controller
    {
        private readonly masterContext _context;

        public VisitsController(masterContext context)
        {
            _context = context;
        }

        // GET: Visits
        public async Task<IActionResult> Index()
        {
            var masterContext = _context.Visits.Include(v => v.Doctor).Include(v => v.Patient);
            return View(await masterContext.ToListAsync());
        }

        // GET: Visits/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var visits = await _context.Visits
                .Include(v => v.Doctor)
                .Include(v => v.Patient)
                .FirstOrDefaultAsync(m => m.IdVisit == id);
            if (visits == null)
            {
                return NotFound();
            }

            return View(visits);
        }

        // GET: Visits/Create
        public IActionResult Create()
        {
            ViewData["DoctorId"] = new SelectList(_context.Workers, "IdWorker", "IdWorker");
            ViewData["PatientId"] = new SelectList(_context.Patients, "Pesel", "Pesel");
            return View();
        }

        // POST: Visits/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdVisit,VisitsDescription,Date,Compleated,PatientId,DoctorId")] Visits visits)
        {
            if (ModelState.IsValid)
            {
                _context.Add(visits);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DoctorId"] = new SelectList(_context.Workers, "IdWorker", "IdWorker", visits.DoctorId);
            ViewData["PatientId"] = new SelectList(_context.Patients, "Pesel", "Pesel", visits.PatientId);
            return View(visits);
        }

        // GET: Visits/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var visits = await _context.Visits.FindAsync(id);
            if (visits == null)
            {
                return NotFound();
            }
            ViewData["DoctorId"] = new SelectList(_context.Workers, "IdWorker", "IdWorker", visits.DoctorId);
            ViewData["PatientId"] = new SelectList(_context.Patients, "Pesel", "Pesel", visits.PatientId);
            return View(visits);
        }

        // POST: Visits/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdVisit,VisitsDescription,Date,Compleated,PatientId,DoctorId")] Visits visits)
        {
            if (id != visits.IdVisit)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(visits);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VisitsExists(visits.IdVisit))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DoctorId"] = new SelectList(_context.Workers, "IdWorker", "IdWorker", visits.DoctorId);
            ViewData["PatientId"] = new SelectList(_context.Patients, "Pesel", "Pesel", visits.PatientId);
            return View(visits);
        }

        // GET: Visits/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var visits = await _context.Visits
                .Include(v => v.Doctor)
                .Include(v => v.Patient)
                .FirstOrDefaultAsync(m => m.IdVisit == id);
            if (visits == null)
            {
                return NotFound();
            }

            return View(visits);
        }

        // POST: Visits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var visits = await _context.Visits.FindAsync(id);
            _context.Visits.Remove(visits);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VisitsExists(int id)
        {
            return _context.Visits.Any(e => e.IdVisit == id);
        }
    }
}

MedMasters-clinic-app/Controllers/WorkersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Klinika.Models;

namespace Klinika.Controllers
{
    public class WorkersController : Controller
    {
        private readonly masterContext _context;

        public WorkersController(masterContext context)
        {
            _context = context;
        }

        // GET: Workers
        public async Task<IActionResult> Index()
        {
            var masterContext = _context.Workers.Include(w => w.Role);
            return View(await masterContext.ToListAsync());
        }

        // GET: Workers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workers = await _context.Workers
                .Include(w => w.Role)
                .FirstOrDefaultAsync(m => m.IdWorker == id);
            if (workers == null)
            {
                return NotFound();
            }

            return View(workers);
        }

        // GET: Workers/Create
        public IActionResult Create()
        {
            ViewData["RoleId"] = new SelectList(_context.Roles, "IdRole", "IdRole");
            return View();
        }

        // POST: Workers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdWorker,Surname,Forename,Login,Password,RoleId")] Workers workers)
        {
            if (ModelState.IsValid)
            {
                _context.Add(workers);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["RoleId"] = new SelectList(_context.Roles, "IdRole", "IdRole", workers.RoleId);
            return View(workers);
        }

        // GET: Workers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workers = await _context.Workers.FindAsync(id);
            if (workers == null)
            {
                return NotFound();
            }
            ViewData["RoleId"] = new SelectList(_context.Roles, "IdRole", "IdRole", workers.RoleId);
            return View(workers);
        }

        // POST: Workers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdWorker,Surname,Forename,Login,Password,RoleId")] Workers workers)
        {
            if (id != workers.IdWorker)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(workers);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WorkersExists(workers.IdWorker))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RoleId"] = new SelectList(_context.Roles, "IdRole", "IdRole", workers.RoleId);
            return View(workers);
        }

        // GET: Workers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workers = await _context.Workers
                .Include(w => w.Role)
                .FirstOrDefaultAsync(m => m.IdWorker == id);
            if (workers == null)
            {
                return NotFound();
            }

            return View(workers);
        }

        // POST: Workers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var workers = await _context.Workers.FindAsync(id);
            _context.Workers.Remove(workers);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WorkersExists(int id)
        {
            return _context.Workers.Any(e => e.IdWorker == id);
        }
    }
}

MedMasters-clinic-app/Views/Menu/Index.cshtml
@{
    ViewData["Title"] = "Menu";
    ViewData["Icon"] = "images/szukaj.png";
}

<div class="menu-name">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1>Menu</h1>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-12 col-md-6 col-lg-4">
            <a asp-controller="Visits" asp-action="Index">
                <div class="our-departments-cont button gradient-bg">
                    <header class="entry-header d-flex flex-wrap align-items-center">
                        <img src="images/kalendarz.png" alt="">
                        <h3>Wizyty</h3>
                    </header>

                    <div class="entry-content">
                        <p>Przegląd wizyt pacjentów. Dodaj, edytuj lub usuń wizytę</p>
                    </div>
                </div>
            </a>
        </div>


        <div class="col-12 col-md-6 col-lg-4">
            <a asp-controller="Patients" asp-action="Index">
                <div class="our-departments-cont button gradient-bg">
                    <header class="entry-header d-flex flex-wrap align-items-center">
                        <img src="images/pacjenci.png" alt="">
                        <h3>Pacjenci</h3>
                    </header>

                    <div class="entry-content">
                        <p>Przegląd oraz zarządzanie listą pacjentów</p>
                    </div>
                </div>
            </a>
        </div>

        <div class="col-12 col-md-6 col-lg-4">
            <a asp-controller="Workers" asp-action="Index">
                <div class="our-departments-cont button gradient-bg">
                    <header class="entry-header d-flex flex-wrap align-items-center">
                        <img src="images/workers.png" alt="">
                        <h3>Pracownicy</h3>
                    </header>

                    <div class="entry-content">
                        <p>Pracownicy kliniki oraz ich dane logowania i role</p>
                    </div>
                </div>
            </a>
        </div>

        <div class="col-12 col-md-6 col-lg-4">
            <a asp-controller="Medicines" asp-action="Index">
                <div class="our-departments-cont button gradient-bg">
                    <header class="entry-header d-flex flex-wrap align-items-center">
                        <img src="images/leki.png" alt="">
                        <h3>Leki</h3>
                    </header>

                    <div class="entry-content">
                        <p>Przegląd magazynu leków. Zarządzaj listą leków</p>
                    </div>
                </div>
            </a>
        </div>

        <div class="col-12 col-md-6 col-lg-4">
            <a asp-controller="DoctorSpecializations" asp-action="Index">
                <div class="our-departments-cont button gradient-bg">
                    <header class="entry-header d-flex flex-wrap align-items-center">
                        <img src="images/lekarz.png" alt="">
                        <h3>Specjaliści</h3>
                    </header>

                    <div class="entry-content">
                        <p>Przegląd listy lekarzy w klinice. Zarządzaj listą lekarzy</p>
                    </div>
                </div>
            </a>
        </div>

        <div class="col-12 col-md-6 col-lg-4">
            <a asp-controller="MedicalSpecializations" asp-action="Index">
                <div class="our-departments-cont button gradient-bg">
                    <header class="entry-header d-flex flex-wrap align-items-center">
                        <img src="images/specjalizacje.png" alt="">
                        <h3>Specjalizacje</h3>
                    </header>

                    <div class="entry-content">
                        <p>Specjalizacje w naszej klinice</p>
                    </div>
                </div>
            </a>
        </div>

        <div class="col-12 col-md-6 col-lg-4">
            <a asp-controller="Home" asp-action="Index">
                <div class="our-departments-cont button gradient-bg">
                    <header class="entry-header d-flex flex-wrap align-items-center">
                        <img src="images/dom.png" alt="">
                        <h3>Powrót</h3>
                    </header>

                    <div class="entry-content">
                        <p>Potrzebujesz informacji? Wróc na stronę główną</p>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>